### ISSUE TITLE
chore: add the missing openebs-lite-sc.yaml to this repo

### ISSUE THREAD

**Issue by kmova** [openebs/dynamic-localpv-provisioner#114]
**Describe the problem/challenge you have**

Match the provisioner YAMLs provided in https://github.com/openebs/charts/tree/gh-pages with those hosted in this repository (https://github.com/openebs/dynamic-localpv-provisioner/tree/develop/deploy/kubectl)  for development. 

**Describe the solution you'd like**
Add the following that includes both hostpath and device storage class:
- https://github.com/openebs/charts/blob/gh-pages/openebs-lite-sc.yaml

While we are at this, it would be nice to add a `make manifest` that can pull in the latest NDM operator directly from NDM repo and using the yamls in this repo generate the required artifacts like: 

* openebs-operator-lite.yaml
* openebs-operator-lite-sc.yaml
* hostpath-operator.yaml
* hospath-operator-sc.yaml

Ref: https://github.com/openebs/jiva-operator/pull/157

**Comment by verma-kunal** [comment]
Hey @kmova , i would like to work on this issue!!
This would be my 1st time contributing here, so I am very new to the community & the project. Some guidance would be really helpful & appreciated 🙂

**Comment by S-ign** [comment]
Hello, is this still open? I was wondering if this is like a practice exercise or something? I was looking at the files, I'm not sure if I'm understanding this correctly but, it looks like only one file that matches, which is the local-hostpath-provisioner.yaml file in https://github.com/openebs/charts/blob/gh-pages/yamls/.

Is the task to:
fork https://github.com/openebs/dynamic-localpv-provisioner
add local-hostpath-provisioner.yaml to /develop/deploy/kubectl
and submit a PR?

**Comment by niladrih** [comment]
Since v4.0.0, the hostpath provisioner no longer supports installation via operator YAMLs.
