### ISSUE TITLE
volume is in pendig state in case of waitforfirstconsumer

### ISSUE THREAD

**Issue by jianghushinian** [openebs/dynamic-localpv-provisioner#142]
Using LocalPV Device mode, I got the same problem as this issue of lvm-localpv https://github.com/openebs/lvm-localpv/issues/31, how to solve it under the current project? do I have to use nodeAffinity to tag my StatefulSet?

according to the description of @zwForrest:

> In the case of waitforfirstconsumer, the pod will be scheduled by [parameters](https://kubernetes.io/docs/reference/scheduling/config/#scheduling-plugins-1), then the node will be selected by scheduler, but lvm did not participate in kubernetes scheduling. This means that the node selected by lvm and the one selected by kubernetes scheduler may not be the same.

k8s cannot sense the local device state of the node when scheduling?

**Comment by niladrih** [comment]
This issue does not apply to v4 and newer versions. Device mode is no longer supported.
