### ISSUE TITLE
change localPVprovisionerName openebs.io/local 

### ISSUE THREAD

**Issue by Yelijah** [openebs/dynamic-localpv-provisioner#143]
**Describe the problem/challenge you have**
I want to change localPVprovisionerName by some config or env. Does any one have any ideas ?

**Comment by niladrih** [comment]
This is not configurable at the moment. You could change the string variable value [here](https://github.com/openebs/dynamic-localpv-provisioner/blob/develop/cmd/provisioner-localpv/app/start.go#L21) and build the container for your use-case `make docker.buildx.provisioner-localpv`.

It would be easy to make this configurable. Closing this issue. Please reopen this if that's something you think would be worthwhile. Please share your use-case, if that is the case.
