### ISSUE TITLE
googleanalytics.go:49] Post "https://www.google-analytics.com/collect"

### ISSUE THREAD

**Issue by matthewei** [openebs/dynamic-localpv-provisioner#158]
**Describe the bug:** A clear and concise description of what the bug is.
The **localpv-provisioner** pod generate the "googleanalytics.go:49] Post "https://www.google-analytics.com/collect": dial tcp 203.208.40.33:443: i/o timeout" 
**Expected behaviour:** 
**we don't want this behavior to happen**, Please help me to avoid it.
**Steps to reproduce the bug:**
you just install it and do nothing.
**The output of the following commands will help us better understand what's going on**:

* `kubectl logs -f --tail 200 -n openebs localpv-localpv-provisioner-9bf5b5874-vblxw`

**Environment details:**
- OpenEBS version (use `kubectl get po -n openebs --show-labels`):  3.4.0,
- Kubernetes version (use `kubectl version`): 1.21

**Comment by sushiMix** [comment]
It is documented in the helm chart
https://github.com/openebs/dynamic-localpv-provisioner/blob/57a57242cdec2dc565a9c94dffed05f71b3bcf7f/deploy/helm/charts/README.md?plain=1#L109

**Comment by niladrih** [comment]
@matthewei disabling the analytics will help with the logs. The error in analytics could be due to a variety of reasons, but it doesn't actively affect the provisioner's behaviour. Disabling analytics should fix this.
