### ISSUE TITLE
Update compatibility matrix

### ISSUE THREAD

**Issue by p3lim** [openebs/dynamic-localpv-provisioner#174]
**Describe the problem/challenge you have**
We're upgrading to a Kubernetes version past the ones listed in the compatibility matrix in the README.

**Describe the solution you'd like**
An update to the compatibility matrix.

**Environment:**
- OpenEBS version (use `kubectl get po -n openebs --show-labels`): 3.5
- Kubernetes version (use `kubectl version`): 1.28
- Cloud provider or hardware configuration: -
- OS (e.g: `cat /etc/os-release`): -
- kernel (e.g: `uname -a`): -
- others: -

**Comment by niladrih** [comment]
Have to update https://github.com/openebs/dynamic-localpv-provisioner/blob/develop/README.md. However, all versions of kubernetes up to 1.29 are supported. I haven't had a chance to test v1.30, but it should work from the looks of it.
