### ISSUE TITLE
Unable to disable analytics reporting

### ISSUE THREAD

**Issue by emosbaugh** [openebs/dynamic-localpv-provisioner#210]
**Describe the bug:** A clear and concise description of what the bug is.

If I disable analytics via the helm values.yaml I still see the provisioner trying to reach out to the analytics service. Outbound requests violate org policies which make the product unusable.

I believe the issue is that the environment variable disables the check that is sent on a schedule but not the one that is sent per events.

https://github.com/openebs/dynamic-localpv-provisioner/blob/2e2234eeae40f7a7e335cb2a35f2534d368231aa/cmd/provisioner-localpv/app/start.go#L86-L91

https://github.com/openebs/dynamic-localpv-provisioner/blob/2e2234eeae40f7a7e335cb2a35f2534d368231aa/cmd/provisioner-localpv/app/provisioner.go#L194-L204

**Expected behaviour:** A concise description of what you expected to happen

Localpv provisioner will not make analytics requests.

**Steps to reproduce the bug:**
Steps to reproduce the bug should be clear and easily reproducible to help people gain an understanding of the problem

Helm install in a server without outbound internet access with values.yaml

```
localpv-provisioner:
  analytics:
    enabled: false
```

**The output of the following commands will help us better understand what's going on**:

* `kubectl get pods -n <openebs_namespace> --show-labels`

```
# kubectl -n openebs get pod -oyaml openebs-localpv-provisioner-864c5b87df-pxmr7
...
    - name: OPENEBS_IO_ENABLE_ANALYTICS
      value: "false"
```

* `kubectl logs <upgrade_job_pod> -n <openebs_namespace>`

```
# kubectl -n openebs logs openebs-localpv-provisioner-864c5b87df-pxmr7
I1107 14:52:48.187292       1 start.go:47] Starting Provisioner...
...
I1107 14:53:56.967132       1 provisioner_hostpath.go:77] Creating volume pvc-aa61ca49-0fca-4fd6-ae7d-1446e8a4722c at node with labels {map[kubernetes.io/hostname:ethanm-ec-1]}, path:/var/lib/embedded-cluster/openebs-local/pvc-aa61ca49-0fca-4fd6-ae7d-1446e8a4722c,ImagePullSecrets:[]
2024-11-07T14:54:01.018Z	INFO	app/provisioner_hostpath.go:215		{"eventcode": "local.pv.provision.success", "msg": "Successfully provisioned Local PV", "rname": "pvc-aa61ca49-0fca-4fd6-ae7d-1446e8a4722c", "storagetype": "hostpath"}
I1107 14:54:01.018295       1 controller.go:1449] provision "kotsadm/kotsadm-rqlite-kotsadm-rqlite-0" class "openebs-hostpath": volume "pvc-aa61ca49-0fca-4fd6-ae7d-1446e8a4722c" provisioned
I1107 14:54:01.018320       1 controller.go:1462] provision "kotsadm/kotsadm-rqlite-kotsadm-rqlite-0" class "openebs-hostpath": succeeded
I1107 14:54:01.018329       1 volume_store.go:212] Trying to save persistentvolume "pvc-aa61ca49-0fca-4fd6-ae7d-1446e8a4722c"
I1107 14:54:01.025417       1 volume_store.go:219] persistentvolume "pvc-aa61ca49-0fca-4fd6-ae7d-1446e8a4722c" saved
I1107 14:54:01.025563       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"kotsadm", Name:"kotsadm-rqlite-kotsadm-rqlite-0", UID:"aa61ca49-0fca-4fd6-ae7d-1446e8a4722c", APIVersion:"v1", ResourceVersion:"1393", FieldPath:""}): type: 'Normal' reason: 'ProvisioningSucceeded' Successfully provisioned volume pvc-aa61ca49-0fca-4fd6-ae7d-1446e8a4722c
E1107 14:53:50.786309       1 usage.go:170] Post "https://www.google-analytics.com/mp/collect?api_secret=91JGdTg9QwGn7Y-vvuM4zA&measurement_id=G-TZGP46618W": dial tcp: lookup www.google-analytics.com on 10.244.128.10:53: read udp 10.244.104.3:37322->8.8.8.8:53: i/o timeout
```

**Anything else we need to know?:**

**Environment details:**
- OpenEBS version (use `kubectl get po -n openebs --show-labels`): `openebs.io/component-name=openebs-localpv-provisioner,openebs.io/version=4.1.1`
- Kubernetes version (use `kubectl version`): `v1.30.5+k0s`
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- kernel (e.g: `uname -a`):
- others:

**Comment by emosbaugh** [comment]
Thanks for the quick turnaround!

**Comment by tiagolobocastro** [comment]
> Thanks for the quick turnaround!

Thanks for the report and quick fix too :)

**Comment by niladrih** [comment]
v4.1.2 ships with the fix.
