### ISSUE TITLE
Dynamic Local PV (hostpath and device) - GitHub Updates

### ISSUE THREAD

**Issue by kmova** [openebs/dynamic-localpv-provisioner#45]
- [x] README Updates 
  - [x] Badges
  - [x] Project Status - Beta
  - [x] k8s version compatibility
  - [x] Quickstart guide 
  - [x] Contributor Docs
  - [x] Adopters.md with links to openebs/openebs adopters
  - [x] Roadmap link to openebs project
  - [x] Community Links 
- [x] Helm Charts
- [x] GitHub Builds
- [x] Multiarch builds
- [x] Disable Travis
- [x] Downstream tagging
- [x] e2e tests
- [ ] Upgrades
- [ ] Monitoring
- [x] Troubleshooting guide

**Comment by niladrih** [comment]
PR for:
- Badges
- Roadmap link
- Project Status: Beta
- Adopters link
- Kubernetes compatibility matrix

https://github.com/openebs/dynamic-localpv-provisioner/pull/93
