### ISSUE TITLE
Populate data into Local PV from another Local PV or from an outside source

### ISSUE THREAD

**Issue by kmova** [openebs/dynamic-localpv-provisioner#60]
A few use cases around Local PV are: 
* Cluster node re-cycle scenarios: A Kubernetes node will be reclaimed by the provider during an upgrade. The data saved into the local storage of the node (about to be recycled) should be migrated to another node in the cluster and the application (pod) using that storage should be re-scheduled to the new node. 
* Load the seed data into Local PV: Either from an external source or as a clone from an existing Local PV volume that will help with scaling the applications with static content (without using read-write many) or for performing ML jobs that require data to be downloaded from an S3 or other sources. 

The idea is to make use of the "Data Populator" and PVC Data Source constructs being developed in K8s to solve these use cases. Can data populators be built using rsync, rclone or restic kind of tools. 

The solution should be easy to integrate into Stateful or other K8s operators. For example, it should be possible to write a generic operator that can be instructed to drain a node by:
- initiating the migration of the Local PVs to an upgraded new node
- move the application 
- allowing the older node to be reclaimed

Alternate ways or workaround available today are:
* Take Backup of the application using Velero to an S3 location and restore the data into new nodes. A few challenges or drawbacks of this approach are: 
  - Setting up backup outside the cluster or creating a new dependency.
  - The backup needs to be performed by scaling down the application. 
  - And if the application belongs to STS - all pods need to coordinate in the process.

**Comment by shovanmaity** [comment]
A prototype of this problem is done [here](https://github.com/shovanmaity/k8s-volume-copy).
[Here](https://github.com/shovanmaity/k8s-volume-copy/tree/main/docs/demo) is the link of how to use it.

**Comment by pawanpraka1** [comment]
fixed via https://github.com/openebs/data-populator
