### ISSUE TITLE
Auto create default storage classes

### ISSUE THREAD

**Issue by kmova** [openebs/dynamic-localpv-provisioner#90]
maya-apiserver was create storage classes based on the configuration passed on by the environment values. With maya-apiserver getting deprecated with 3.0, the automatic creation of storage class should be handled by this provisioner. 

https://github.com/openebs/maya/blob/master/pkg/install/v1alpha1/localpv_sc.go

**Comment by kmova** [comment]
This can be added as a template in openebs helm chart  - just like how it is here in the local PV helm chart.

**Comment by niladrih** [comment]
StorageClass creation is no longer handled by maya-apiserver. 
In the openebs/openebs helm chart, openebs-hostpath and openebs-device StorageClasses are created using template YAML files.
In the openebs-operator.yaml (v2.12.1), openebs-hostpath and openebs-device StorageClasses are created using YAMLs added on to to the existing set.

Relevant PRs:
1. https://github.com/openebs/maya/pull/1816
2. https://github.com/openebs/charts/pull/257
3. https://github.com/openebs/charts/pull/270
4. https://github.com/openebs/charts/pull/258

This issue has been resolved. Closing this.
